services:
  database:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django-server:
    container_name: django-server
    build:
      context: ./DataServer
      dockerfile: Dockerfile
    volumes:
      - ./DataServer:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "cd /app && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

      
volumes:
  postgres_data: