services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./DataServer
      dockerfile: Dockerfile
    image: backend
    volumes:
      - ./DataServer:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    image: nginx:latest
    volumes:
      - ./frontend-vue/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      
volumes:
  postgres_data: