# Generated by Django 5.0.2 on 2024-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceFile', models.CharField(max_length=100)),
                ('sourceFileDate', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('recipient', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
