# Generated by Django 5.0.2 on 2024-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0002_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sourceFileDate',
            field=models.DateTimeField(),
        ),
    ]
