# Generated by Django 5.0.2 on 2024-02-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0003_alter_transaction_sourcefiledate'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceFile', models.CharField(max_length=100)),
                ('sourceFileDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sourceFile',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sourceFileDate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.file'),
        ),
    ]
