# Generated by Django 5.0.2 on 2024-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0004_file_remove_transaction_sourcefile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='file',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fileDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fileID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fileName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
