# Generated by Django 5.0.2 on 2024-02-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0005_remove_transaction_file_transaction_filedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowFirst', models.IntegerField()),
                ('rowLast', models.IntegerField()),
                ('colDate', models.IntegerField()),
                ('colRecipient', models.IntegerField()),
                ('colDescription', models.IntegerField()),
                ('colAmount', models.IntegerField()),
                ('delimiter', models.CharField(max_length=1)),
                ('valueType', models.CharField(max_length=100)),
            ],
        ),
    ]
