# Generated by Django 5.0.2 on 2024-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0006_importschema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importschema',
            name='valueType',
        ),
        migrations.AddField(
            model_name='importschema',
            name='decimalSeparator',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='importschema',
            name='thousandsSeparator',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colAmount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colDate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colDescription',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colRecipient',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='delimiter',
            field=models.CharField(default=';', max_length=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='rowFirst',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='rowLast',
            field=models.IntegerField(default=0),
        ),
    ]
