# Generated by Django 5.0.2 on 2024-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0008_importschema_dateformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fileID',
        ),
    ]
