# Generated by Django 5.0.2 on 2024-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0010_category_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expense',
        ),
        migrations.AddField(
            model_name='category',
            name='transactionType',
            field=models.CharField(default='Expense', max_length=100, null=True),
        ),
    ]
