# Generated by Django 5.0.2 on 2024-03-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0012_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='keywords',
            field=models.ManyToManyField(related_name='transaction', to='REST_API.assignment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='overruled',
            field=models.BooleanField(default=False),
        ),
    ]
