# Generated by Django 5.0.2 on 2024-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0014_alter_transaction_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='keywords',
            new_name='assignments',
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colAmount',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colDescription',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='importschema',
            name='colRecipient',
            field=models.IntegerField(default=2),
        ),
    ]
