# Generated by Django 5.0.2 on 2024-03-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0015_rename_keywords_transaction_assignments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transactionType',
        ),
    ]
