# Generated by Django 5.0.2 on 2024-03-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0016_remove_category_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
