# Generated by Django 5.0.2 on 2024-03-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0018_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
