# Generated by Django 5.0.2 on 2024-03-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0020_rename_decimalplaces_setting_rounding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='checkDescription',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='checkRecipient',
        ),
        migrations.AddField(
            model_name='assignment',
            name='checkMode',
            field=models.CharField(default='recipient_only', max_length=100),
            preserve_default=False,
        ),
    ]
