# Generated by Django 5.0.2 on 2024-03-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0021_remove_assignment_checkdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#444444', max_length=7),
        ),
    ]
