# Generated by Django 5.0.2 on 2024-03-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0022_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='rounding',
        ),
        migrations.AddField(
            model_name='setting',
            name='locale',
            field=models.CharField(default='de_DE', max_length=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.category'),
        ),
    ]
