# Generated by Django 5.0.2 on 2024-04-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0025_userprofile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
