# Generated by Django 5.0.2 on 2024-04-14 15:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0028_delete_importschema_assignment_user_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='colAmount',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colDate',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colDescription',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colRecipient',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=encrypted_model_fields.fields.EncryptedCharField(default='€'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='dateFormat',
            field=encrypted_model_fields.fields.EncryptedCharField(default='DD.MM.YYYY'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='decimalSeparator',
            field=encrypted_model_fields.fields.EncryptedCharField(default=','),
        ),
        migrations.AlterField(
            model_name='setting',
            name='delimiter',
            field=encrypted_model_fields.fields.EncryptedCharField(default=';'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='locale',
            field=encrypted_model_fields.fields.EncryptedCharField(default='de-DE'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rowFirst',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rowLast',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='thousandsSeparator',
            field=encrypted_model_fields.fields.EncryptedCharField(default='.'),
        ),
    ]
