# Generated by Django 5.0.2 on 2024-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0029_alter_setting_colamount_alter_setting_coldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='colAmount',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colDate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colDescription',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='setting',
            name='colRecipient',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(default='€', max_length=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='dateFormat',
            field=models.CharField(default='DD.MM.YYYY', max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='decimalSeparator',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='delimiter',
            field=models.CharField(default=';', max_length=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='locale',
            field=models.CharField(default='de-DE', max_length=5),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rowFirst',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rowLast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='thousandsSeparator',
            field=models.CharField(default='.', max_length=1),
        ),
    ]
