# Generated by Django 5.0.2 on 2024-04-14 15:18

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0030_alter_setting_colamount_alter_setting_coldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='checkMode',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='keyword',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=encrypted_model_fields.fields.EncryptedCharField(default='#444444'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=encrypted_model_fields.fields.EncryptedDateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fileDate',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fileName',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overruled',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
