# Generated by Django 5.0.2 on 2024-04-15 17:02

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0031_alter_assignment_checkmode_alter_assignment_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uploadID',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
    ]
