# Generated by Django 5.0.2 on 2024-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0032_transaction_uploadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uploadID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
