# Generated by Django 5.0.2 on 2024-05-04 03:45

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0035_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
    ]
