# Generated by Django 5.0.2 on 2024-05-13 13:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0037_alter_transaction_amount_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='NONE'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='NONE'),
        ),
    ]
