# Generated by Django 5.0.2 on 2024-05-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0038_alter_transaction_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='checkMode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#444444', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overruled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='REST_API.period'),
        ),
    ]
