# Generated by Django 5.0.2 on 2024-05-14 02:49

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0038_alter_transaction_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='assignments',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REST_API.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=encrypted_model_fields.fields.EncryptedDateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=encrypted_model_fields.fields.EncryptedCharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overruled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=encrypted_model_fields.fields.EncryptedCharField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1)),
                ('monthName', models.CharField(default='January', max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('quarter', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REST_API.period'),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.category')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='assignments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REST_API.assignment'),
        ),
    ]
