# Generated by Django 5.0.2 on 2024-05-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0039_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='assignments',
        ),
        migrations.AddField(
            model_name='transaction',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REST_API.assignment'),
        ),
    ]
