# Generated by Django 5.0.2 on 2024-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0039_alter_assignment_checkmode_alter_assignment_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
