# Generated by Django 5.0.2 on 2024-08-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0040_period_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='comment',
        ),
    ]
