# Generated by Django 5.0.2 on 2024-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0040_remove_transaction_assignments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='user',
        ),
        migrations.AddField(
            model_name='period',
            name='fromDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='toDate',
            field=models.DateField(null=True),
        ),
    ]
