# Generated by Django 5.0.2 on 2024-05-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0042_period_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='monthName',
        ),
        migrations.RemoveField(
            model_name='period',
            name='user',
        ),
    ]
