
### REGISTER
POST http://localhost:8000/auth/register/
content-type: application/json

{
    "username": "Preis2",
    "password": "1234"
}

### LOGIN
POST http://localhost:8000/auth/login/
content-type: application/json

{
    "username": "Edda",
    "password": "edda"
}

### DELETE USER
POST http://localhost:8000/auth/deleteUser/
content-type: application/json
Authorization: ff05b402165a5ab6322bb7ab72dd58d0058c85ca
    
    {
        "username": "Preis2"
    }

### UPDATE PASSWORD
POST http://localhost:8000/auth/updatePassword/
content-type: application/json
Authorization: cb3c344e6aee9ab4066fa4c67895ee4398621e9c

{
    "username": "Preis",
    "currentPassword": "edda",
    "newPassword": "edda"
}

### GET SETTINGS
GET http://localhost:8000/api/settings/
content-type: application/json
Authorization: Token 87c69d57a68cc6aa98e2c5122432454bf252021b